StylesPath = vale/styles

MinAlertLevel = suggestion

Vocab = DX

# Global settings (applied to every syntax)
[*]


# Syntax-specific settings
# These overwrite any conflicting global settings
[*.{md,MD,TXT,txt}]

BasedOnStyles = DX, Microsoft